

#compilation 
# gcc mlxtest.c -L/nfs/homes/ael-moha/Documents/1337/1337-/ft_fdf/minilibx-linux 
# -I/nfs/homes/ael-moha/Documents/1337/1337-/ft_fdf/minilibx-linux 
# -lmlx_Linux -lXext -lX11 -lm -lz -o mlx_executable


#include => $(NAME), all, clean, fclean and re
clean:
	rm -f *.o